#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("ResideMenu.Demo.Resource", IsApplication=true)]

namespace ResideMenu.Demo
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::ResideMenu.Resource.Drawable.shadow = global::ResideMenu.Demo.Resource.Drawable.shadow;
			global::ResideMenu.Resource.Id.iv_background = global::ResideMenu.Demo.Resource.Id.iv_background;
			global::ResideMenu.Resource.Id.iv_icon = global::ResideMenu.Demo.Resource.Id.iv_icon;
			global::ResideMenu.Resource.Id.iv_shadow = global::ResideMenu.Demo.Resource.Id.iv_shadow;
			global::ResideMenu.Resource.Id.layout_left_menu = global::ResideMenu.Demo.Resource.Id.layout_left_menu;
			global::ResideMenu.Resource.Id.layout_right_menu = global::ResideMenu.Demo.Resource.Id.layout_right_menu;
			global::ResideMenu.Resource.Id.sv_left_menu = global::ResideMenu.Demo.Resource.Id.sv_left_menu;
			global::ResideMenu.Resource.Id.sv_right_menu = global::ResideMenu.Demo.Resource.Id.sv_right_menu;
			global::ResideMenu.Resource.Id.tv_title = global::ResideMenu.Demo.Resource.Id.tv_title;
			global::ResideMenu.Resource.Layout.residemenu = global::ResideMenu.Demo.Resource.Layout.residemenu;
			global::ResideMenu.Resource.Layout.residemenu_item = global::ResideMenu.Demo.Resource.Layout.residemenu_item;
			global::ResideMenu.Resource.String.app_name = global::ResideMenu.Demo.Resource.String.app_name;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int button = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int button_on = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int button_selector = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int frame = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int gesture = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_launcher = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int icon_calendar = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int icon_home = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int icon_profile = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int icon_settings = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int menu_background = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int shadow = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int title_bar_menu = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int title_bar_menu_on = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int titlebar_menu_selector = 2130837518;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060004
			public const int btn_open_menu = 2131099652;
			
			// aapt resource value: 0x7f060001
			public const int ignored_view = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int imageView = 2131099650;
			
			// aapt resource value: 0x7f06000a
			public const int iv_background = 2131099658;
			
			// aapt resource value: 0x7f060010
			public const int iv_icon = 2131099664;
			
			// aapt resource value: 0x7f06000b
			public const int iv_shadow = 2131099659;
			
			// aapt resource value: 0x7f06000d
			public const int layout_left_menu = 2131099661;
			
			// aapt resource value: 0x7f06000f
			public const int layout_right_menu = 2131099663;
			
			// aapt resource value: 0x7f060006
			public const int layout_top = 2131099654;
			
			// aapt resource value: 0x7f060000
			public const int listView = 2131099648;
			
			// aapt resource value: 0x7f060009
			public const int main_fragment = 2131099657;
			
			// aapt resource value: 0x7f06000c
			public const int sv_left_menu = 2131099660;
			
			// aapt resource value: 0x7f06000e
			public const int sv_right_menu = 2131099662;
			
			// aapt resource value: 0x7f060003
			public const int textView = 2131099651;
			
			// aapt resource value: 0x7f060005
			public const int textView1 = 2131099653;
			
			// aapt resource value: 0x7f060007
			public const int title_bar_left_menu = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int title_bar_right_menu = 2131099656;
			
			// aapt resource value: 0x7f060011
			public const int tv_title = 2131099665;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int calendar = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int home = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int profile = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int residemenu = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int residemenu_item = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int settings = 2130903046;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int fragment_text = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
